repositories:
  phone-numbers:
    queries:
      find-all-phone-numbers: >
        SELECT id, customer_id, phone_number, is_active FROM phone_numbers
        ORDER by phone_number ASC
        OFFSET :offset
        LIMIT :limit
      count-all: >
        SELECT count(*) from phone_numbers
      count-by-phone-number: >
        SELECT count(*) FROM phone_numbers
        where phone_number = :phoneNumber
      find-by-phone-number: >
        SELECT id, customer_id, phone_number, is_active FROM phone_numbers
        where phone_number = :phoneNumber
      activate-by-phone-number: >
        UPDATE phone_numbers
        SET is_active = true
        WHERE phone_number = :phoneNumber
        AND is_active = false

pagination:
  page-size: 25